[package]
name = "stutter"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "An API capturing computations which can be subdivided into smaller steps"
repository = "https://github.com/DavePearce/Stutter.rs"

[dependencies]
